### ISSUE TITLE
Create Mockups

### ISSUE THREAD

**Issue by WietseSteenmans** [WietseSteenmans/Cloud_Applications#8]
-Website (frontend + backend)
-Mobile app

**Comment by Wizla** [comment]
![mockup1](https://cloud.githubusercontent.com/assets/17495791/18864593/5e6d8384-8497-11e6-9e0a-62f03ee427a0.png)

**Comment by Wizla** [comment]
Website Mockup

**Comment by WietseSteenmans** [comment]
![mobile app mockup](https://cloud.githubusercontent.com/assets/17495855/18864803/3dc03c8e-8498-11e6-84b3-2d69f3123e46.jpg)

**Comment by Wizla** [comment]
![mockup_backend](https://cloud.githubusercontent.com/assets/17495791/18992120/daf98876-871c-11e6-9b67-d6490ecc4200.png)
